Implement MockHTTPResponse.close
betamaxpy/betamax pull request #201
Opened 2023-08-17 06:11 UTC by iv-m

https://github.com/betamaxpy/betamax/issues/200

2023-12-23 04:09 UTC, jhatler commented
I merged #202, #205, and #206 on my fork and then rebased this commit onto them. I updated the commit slightly to pass the docstring checks. All of the tox checks pass in my build here:

https://github.com/jhatler/betamax/pull/6

Once #202, #205, and #206 are merge, I think this can be as well.

Once this is merged, #200 should be fixed as this project will be compatible with urllib3 v2.

2024-02-05 20:32 UTC, IvanAnishchuk commented
Could this be a good time to revive this? Is any work still required before this can be merged?

2024-02-05 21:54 UTC, sigmavirus24 commented
> Could this be a good time to revive this? Is any work still required before this can be merged?

If @iv-m wants to rebase this I'd merge it. If someone else wants to resubmit on their behalf that's fine by me too

2024-02-06 04:43 UTC, iv-m commented
> If @iv-m wants to rebase this I'd merge it.

Done)

2024-02-06 12:40 UTC, sigmavirus24 requested changes

2024-02-06 12:40 UTC, sigmavirus24 commented on src/betamax/mock_response.py
> +        self.__closed = True
```suggestion
        self._closed = True
```

2024-02-06 12:42 UTC, sigmavirus24 approved these changes

2024-02-06 12:44 UTC, merged

2024-02-08 14:03 UTC, sigmavirus24 commented
0.9.0 has been released with this. Thank you @iv-m @jhatler